version: '3.8'

services:
  test_req:
    container_name: test_req
    build: test_req/
    networks:
      - lb_network
  lb:
    container_name: lb
    build: lb/
    ports:
      - "80:80"
    networks:
      - lb_network
  web_1:
    container_name: web_1
    build: web_server/
    networks:
      - lb_network
  web_2:
    container_name: web_2
    build: web_server/
    networks:
      - lb_network
  web_3:
    container_name: web_3
    build: web_server/
    networks:
      - lb_network
  web_4:
    container_name: web_4
    build: web_server/
    networks:
      - lb_network
  sql:
    container_name: sql
    build: sql/
    networks:
      - lb_network    
  grafana:
    image: grafana/grafana
    container_name: grafana_log
    ports:
      - 3000:3000
    restart: unless-stopped
    volumes:
      - grafana-data:/Users/Shared/grafana
      - grafana-conf:/Users/Shared/grafana/conf
volumes:
  grafana-data:
  grafana-conf:

networks:
  lb_network:
    driver: bridge